name: 'Frontend Landing Page Docker Build and Push'
description: 'Builds and pushes an Astro landing page Docker image optimized for static site generation'

inputs:
  image-name:
    description: 'Name of the Docker image'
    required: true
    default: 'frontend-landing'
  github-token:
    description: 'GitHub token for authentication'
    required: true
  docker-username:
    description: 'Docker Hub username'
    required: false
  docker-password:
    description: 'Docker Hub password'
    required: false
  deliver:
    description: 'Whether to push to registries'
    required: false
    default: 'true'
  build-env:
    description: 'Build environment (development, staging, production)'
    required: false
    default: 'production'
  dockerfile:
    description: 'Path to Dockerfile'
    required: false
    default: './client/apps/marketing/Dockerfile'
  context:
    description: 'Build context'
    required: false
    default: '.'
  base-url:
    description: 'Base URL for the landing page'
    required: false
    default: ''

outputs:
  image-full-name:
    description: 'Full name of the built image including registry and tag'
    value: ${{ steps.image-info.outputs.image-full-name }}
  image-tags:
    description: 'Tags applied to the image'
    value: ${{ steps.meta.outputs.tags }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js and pnpm
      uses: ./.github/actions/setup/node

    - name: Set up Docker Buildx
      # Pinned to v3 commit hash for security
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

    - name: Login to GitHub Container Registry
      id: ghcr-login
      # Pinned to v3 commit hash for security
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
      continue-on-error: true
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.github-token }}

    - name: Handle GHCR login failure
      if: steps.ghcr-login.outcome != 'success'
      shell: bash
      run: |
        echo "❌ Failed to authenticate with GitHub Container Registry"
        echo "🔍 Common authentication issues:"
        echo "  - GitHub token may have expired"
        echo "  - GitHub token may not have required permissions (write:packages, read:packages)"
        echo "  - GitHub Container Registry may be experiencing issues"
        echo "  - Network connectivity problems"

        if [ "${{ inputs.deliver }}" == "true" ]; then
          echo "⚠️ Authentication failure will prevent pushing to GHCR"
          echo "⚠️ Build will continue but delivery to GHCR will fail"
        fi

    - name: Login to Docker Hub
      id: dockerhub-login
      if: inputs.docker-username != '' && inputs.docker-password != ''
      # Pinned to v3 commit hash for security
      uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
      continue-on-error: true
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: Handle Docker Hub login failure
      if: inputs.docker-username != '' && inputs.docker-password != '' && steps.dockerhub-login.outcome != 'success'
      shell: bash
      run: |
        echo "❌ Failed to authenticate with Docker Hub"
        echo "🔍 Common authentication issues:"
        echo "  - Docker Hub credentials may be incorrect"
        echo "  - Docker Hub account may have 2FA enabled requiring a personal access token"
        echo "  - Docker Hub may be experiencing issues"
        echo "  - Network connectivity problems"

        if [ "${{ inputs.deliver }}" == "true" ]; then
          echo "⚠️ Authentication failure will prevent pushing to Docker Hub"
          echo "⚠️ Build will continue but delivery to Docker Hub will fail"
        fi

    - name: Extract metadata for Docker
      id: meta
      # Pinned to v5 commit hash for security
      uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5
      with:
        images: |
          ghcr.io/${{ github.repository }}/${{ inputs.image-name }}
          ${{ inputs.docker-username != '' && format('{0}/{1}', inputs.docker-username, inputs.image-name) || '' }}
        tags: |
          type=ref,event=branch
          type=ref,event=tag
          type=sha,format=long

    - name: Prepare build arguments
      id: build-args
      shell: bash
      run: |
        # Prepare build arguments with newline separation for docker/build-push-action
        BUILD_ARGS="BUILD_ENV=${{ inputs.build-env }}"

        # Add Base URL if provided
        if [ -n "${{ inputs.base-url }}" ]; then
          BUILD_ARGS="$BUILD_ARGS
          BASE_URL=${{ inputs.base-url }}"
        fi

        echo "args<<EOF" >> $GITHUB_OUTPUT
        echo "$BUILD_ARGS" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

        echo "📋 Build arguments:"
        echo "$BUILD_ARGS" | sed 's/^/  /'

    - name: Create Dockerfile if it doesn't exist
      shell: bash
      run: |
        DOCKERFILE_PATH="${{ inputs.dockerfile }}"
        DOCKERFILE_DIR=$(dirname "$DOCKERFILE_PATH")

        if [ ! -f "$DOCKERFILE_PATH" ]; then
          echo "⚠️ Dockerfile not found at $DOCKERFILE_PATH, creating one..."

          # Create directory if it doesn't exist
          mkdir -p "$DOCKERFILE_DIR"

          # Create a Dockerfile optimized for Astro static site
          cat > "$DOCKERFILE_PATH" << 'EOF'
          # Multi-stage build for Astro landing page

          # Build stage
          FROM node:22-alpine AS build

          # Install pnpm
          RUN corepack enable && corepack prepare pnpm@10.13.1 --activate

          # Set working directory
          WORKDIR /app

          # Copy package files for dependency installation
          COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
          COPY client/config/package.json ./client/config/
          COPY client/packages/tsconfig/package.json ./client/packages/tsconfig/
          COPY client/packages/utilities/package.json ./client/packages/utilities/
          COPY client/apps/marketing/package.json ./client/apps/marketing/

          # Install dependencies
          RUN pnpm install --frozen-lockfile

          # Copy source code
          COPY client/config ./client/config/
          COPY client/packages ./client/packages/
          COPY client/apps/marketing ./client/apps/marketing/

          # Build utilities package first
          RUN pnpm --filter @loomify/utilities build

          # Build the landing page with environment-specific configuration
          ARG BUILD_ENV=production
          ENV NODE_ENV=${BUILD_ENV}

          # Set any additional environment variables for the build
          ARG BASE_URL
          ENV PUBLIC_BASE_URL=${BASE_URL}

          # Build the application
          WORKDIR /app/client/apps/marketing
          RUN pnpm build

          # Production stage - using nginx for static file serving
          FROM nginx:alpine AS production

          # Copy nginx configuration
          RUN cat <<'EOF' > /etc/nginx/conf.d/default.conf
          server {
              listen 80;
              server_name _;
              root /usr/share/nginx/html;
              index index.html;
              location / {
                  try_files $uri $uri/ /index.html;
              }
              error_page 404 /404.html;
              # Enable gzip compression
              gzip on;
              gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
              gzip_comp_level 6;
              gzip_min_length 1000;
          }
          EOF

          # Copy built files from build stage
          COPY --from=build /app/client/apps/marketing/dist /usr/share/nginx/html

          # Install curl for healthcheck
          RUN apk add --no-cache curl

          # Create required directories with proper permissions
          RUN mkdir -p /var/cache/nginx /var/run \
              && chown -R 101:101 /var/cache/nginx /var/run

          # Expose port
          EXPOSE 80

          # Switch to non-root user (nginx)
          USER 101:101

          # Health check
          HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
            CMD curl -f http://localhost/ || exit 1

          # Start nginx
          CMD ["nginx", "-g", "daemon off;"]
          EOF

                    echo "✅ Dockerfile created at $DOCKERFILE_PATH"
                  else
                    echo "✅ Using existing Dockerfile at $DOCKERFILE_PATH"
                  fi



    - name: Build and push Docker image
      id: build
      # Pinned to v5 commit hash for security
      uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: ${{ inputs.deliver == 'true' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: ${{ steps.build-args.outputs.args }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        provenance: false
        outputs: type=image,name=${{ inputs.image-name }},push-by-digest=true,name-canonical=true,push=${{ inputs.deliver == 'true' }}

    - name: Log build cache status
      shell: bash
      run: |
        echo "🔍 Docker build cache information:"
        echo "  Cache from: type=gha"
        echo "  Cache to: type=gha,mode=max"

        # Check if cache was used
        if docker buildx du 2>/dev/null | grep -q "cache"; then
          echo "✅ Build cache was utilized"
          CACHE_SIZE=$(docker buildx du 2>/dev/null | grep "cache" | awk '{print $1}')
          echo "  Cache size: $CACHE_SIZE"
        else
          echo "⚠️ No build cache was utilized or cache information unavailable"
        fi

    - name: Handle build errors
      id: error-handler
      if: failure() && steps.build.outcome == 'failure'
      shell: bash
      run: |
        echo "❌ Astro landing page Docker image build failed"
        echo "🔍 Common issues to check:"
        echo "  - Node.js dependency issues"
        echo "  - TypeScript compilation errors"
        echo "  - Astro build configuration"
        echo "  - Environment variable configuration"
        echo "  - Disk space or memory constraints"

        # Create log directory for build output
        mkdir -p /tmp/build-logs
        ERROR_LOG="/tmp/build-logs/astro-build-error.log"

        # Capture Docker build logs if available
        docker buildx ls &> /dev/null
        if [ $? -eq 0 ]; then
          echo "📋 Capturing Docker build logs..."
          docker buildx du 2>/dev/null > $ERROR_LOG
          docker buildx ls 2>/dev/null >> $ERROR_LOG
        fi

        # Check for common Astro errors in the logs
        if grep -q "ERR_PNPM" $GITHUB_STEP_SUMMARY 2>/dev/null; then
          echo "⚠️ pnpm dependency resolution error detected"
          echo "  - Check pnpm-lock.yaml for inconsistencies"
          echo "  - Verify package.json dependencies"
          echo "  - Try clearing pnpm cache and rebuilding"
        fi

        if grep -q "TypeScript error" $GITHUB_STEP_SUMMARY 2>/dev/null; then
          echo "⚠️ TypeScript compilation error detected"
          echo "  - Check for type errors in your code"
          echo "  - Verify tsconfig.json configuration"
          echo "  - Ensure all required type definitions are installed"
        fi

        if grep -q "Astro error" $GITHUB_STEP_SUMMARY 2>/dev/null; then
          echo "⚠️ Astro build error detected"
          echo "  - Check astro.config.mjs for configuration issues"
          echo "  - Verify Astro component syntax"
          echo "  - Check for compatibility issues with Astro plugins"
        fi

        if grep -q "ENOSPC" $GITHUB_STEP_SUMMARY 2>/dev/null; then
          echo "⚠️ Disk space issue detected"
          echo "  - Free up disk space on the runner"
          echo "  - Consider optimizing build to use less disk space"
        fi

        if grep -q "network timeout" $GITHUB_STEP_SUMMARY 2>/dev/null; then
          echo "⚠️ Network timeout detected"
          echo "  - Check network connectivity"
          echo "  - Consider increasing timeout values"
          echo "  - Try using a different registry mirror"
        fi

        # Check Docker daemon status
        if ! docker info &>/dev/null; then
          echo "⚠️ Docker daemon issue detected"
          echo "  - Docker daemon may not be running"
          echo "  - Check Docker service status"
          echo "  - Verify Docker socket permissions"
        fi

        # Upload error log as artifact
        echo "::group::Upload error log"
        if [ -f "$ERROR_LOG" ]; then
          echo "build-error-log=$ERROR_LOG" >> $GITHUB_OUTPUT
          echo "⚠️ Error log captured for debugging"
        fi
        echo "::endgroup::"

        echo "⚠️ For detailed troubleshooting, check the workflow run logs"

        exit 1

    - name: Extract first tag
      id: first-tag
      shell: bash
      run: |
        # Extract the first tag from the multiline output
        FIRST_TAG=$(echo "${{ steps.meta.outputs.tags }}" | head -n 1)
        echo "value=$FIRST_TAG" >> $GITHUB_OUTPUT

    - name: Scan Docker image for vulnerabilities
      uses: ./.github/actions/docker/security-scan
      with:
        image-ref: ${{ steps.first-tag.outputs.value }}@${{ steps.build.outputs.digest }}
        report-name: ${{ inputs.image-name }}-security-scan
        category: frontend-landing-trivy
        severity: 'HIGH,CRITICAL'
        fail-on-error: 'false'

    - name: Set image info for outputs
      id: image-info
      shell: bash
      run: |
        # Get the first tag as the primary image reference
        FIRST_TAG=$(echo "${{ steps.meta.outputs.tags }}" | head -n 1)
        echo "image-full-name=$FIRST_TAG" >> $GITHUB_OUTPUT

        echo "📋 Image build summary:"
        echo "  Primary image: $FIRST_TAG"
        echo "  All tags: ${{ steps.meta.outputs.tags }}"
        echo "  Labels: ${{ steps.meta.outputs.labels }}"
        echo "  Build environment: ${{ inputs.build-env }}"

        # Get image details if available
        if docker inspect "$FIRST_TAG" &>/dev/null; then
          echo "  Image ID: $(docker inspect --format='{{.Id}}' "$FIRST_TAG" | cut -d':' -f2 | cut -c1-12)"
          echo "  Created: $(docker inspect --format='{{.Created}}' "$FIRST_TAG")"
          echo "  Size: $(docker inspect --format='{{.Size}}' "$FIRST_TAG" | numfmt --to=iec-i --suffix=B --format="%.2f")"
          echo "  Architecture: $(docker inspect --format='{{.Architecture}}' "$FIRST_TAG")"
          echo "  OS: $(docker inspect --format='{{.Os}}' "$FIRST_TAG")"
        fi

        # Log cache information for debugging
        echo "🔍 Cache information:"
        echo "  pnpm cache: $(ls -la $PNPM_STORE_PATH 2>/dev/null | wc -l 2>/dev/null || echo "unavailable") entries"

        # Get Docker cache info
        CACHE_INFO=$(docker buildx du -v 2>/dev/null || echo "")
        if [ -n "$CACHE_INFO" ]; then
          CACHE_COUNT=$(echo "$CACHE_INFO" | grep -c "cache" || echo "0")
          CACHE_SIZE=$(echo "$CACHE_INFO" | grep "cache" | awk '{sum+=$1} END {print sum}')
          echo "  Docker cache entries: $CACHE_COUNT"
          if [ -n "$CACHE_SIZE" ] && [ "$CACHE_SIZE" != "0" ]; then
            echo "  Docker cache size: $CACHE_SIZE"
          fi

          # Check cache hit ratio if available
          CACHE_HITS=$(echo "$CACHE_INFO" | grep -c "hit" || echo "0")
          CACHE_MISSES=$(echo "$CACHE_INFO" | grep -c "miss" || echo "0")
          if [ "$CACHE_HITS" -gt 0 ] || [ "$CACHE_MISSES" -gt 0 ]; then
            TOTAL=$((CACHE_HITS + CACHE_MISSES))
            if [ "$TOTAL" -gt 0 ]; then
              HIT_RATIO=$((CACHE_HITS * 100 / TOTAL))
              echo "  Cache hit ratio: ${HIT_RATIO}% ($CACHE_HITS hits, $CACHE_MISSES misses)"
            fi
          fi
        else
          echo "  Docker cache: information unavailable"
        fi

        # Log registry information
        if [ "${{ inputs.deliver }}" == "true" ]; then
          echo "📦 Registry information:"
          echo "  GHCR: ghcr.io/${{ github.repository }}/${{ inputs.image-name }}"
          if [ -n "${{ inputs.docker-username }}" ]; then
            echo "  Docker Hub: ${{ inputs.docker-username }}/${{ inputs.image-name }}"
          fi

          # Check registry connectivity
          echo "  Registry connectivity:"
          if curl -s -o /dev/null -w "%{http_code}" https://ghcr.io/v2/ 2>/dev/null | grep -q "200\|401"; then
            echo "    GHCR: ✅ Available"
          else
            echo "    GHCR: ⚠️ Connectivity issues"
          fi

          if [ -n "${{ inputs.docker-username }}" ]; then
            if curl -s -o /dev/null -w "%{http_code}" https://registry.hub.docker.com/v2/ 2>/dev/null | grep -q "200\|401"; then
              echo "    Docker Hub: ✅ Available"
            else
              echo "    Docker Hub: ⚠️ Connectivity issues"
            fi
          fi
        fi

        # Log build performance metrics
        echo "⏱️ Build performance metrics:"
        BUILD_DURATION=${{ steps.build.outputs.elapsed }}
        if [ -n "$BUILD_DURATION" ]; then
          echo "  Build duration: $BUILD_DURATION seconds"
        else
          echo "  Build duration: information unavailable"
        fi
