name: 'Setup Java'
description: 'Sets up Java and Gradle with caching'

inputs:
  java-version:
    description: 'Java version to use'
    required: false
    default: '21'
  distribution:
    description: 'Java distribution to use'
    required: false
    default: 'temurin'

runs:
  using: "composite"
  steps:
    - name: Set up JDK
      # Pinned to v4 commit hash for security
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}
        cache: gradle

    - name: Setup Gradle
      # Pinned to v3 commit hash for security
      uses: gradle/actions/setup-gradle@d9c87d481d55275bb5441eef3fe0e46805f9ef70 # v3
      with:
        gradle-version: wrapper
