# Rate-Limiting Configuration for Production
# This file shows recommended production settings for rate limiting

application:
  rate-limit:
    enabled: true

    # Authentication endpoints - stricter limits for production
    auth:
      enabled: true
      endpoints:
        - /api/auth/login
        - /api/auth/register
        - /api/auth/password/reset
        - /api/auth/refresh-token
        - /api/auth/token/refresh
        - /api/auth/federated

      # Multiple layers of protection
      limits:
        # Layer 1: Very strict burst protection
        - name: burst-protection
          capacity: 5
          refill-tokens: 5
          refill-duration: 30s

        # Layer 2: Per-minute limit
        - name: per-minute
          capacity: 10
          refill-tokens: 10
          refill-duration: 1m

        # Layer 3: Per-hour limit
        - name: per-hour
          capacity: 50
          refill-tokens: 50
          refill-duration: 1h

        # Layer 4: Daily limit
        - name: per-day
          capacity: 200
          refill-tokens: 200
          refill-duration: 24h

    # Business endpoints - adjusted for production load
    business:
      enabled: true
      pricing-plans:
        free:
          name: free-plan
          capacity: 100
          refill-tokens: 100
          refill-duration: 1h

        basic:
          name: basic-plan
          capacity: 500
          refill-tokens: 500
          refill-duration: 1h

        professional:
          name: professional-plan
          capacity: 5000
          refill-tokens: 5000
          refill-duration: 1h

        enterprise:
          name: enterprise-plan
          capacity: 50000
          refill-tokens: 50000
          refill-duration: 1h

