# ===================================================================
# To enable TLS generate a certificate using:
# keytool -genkey -alias Loomify -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650
#
# You can also use Let's Encrypt:
# See details in topic "Create a Java Keystore (.JKS) from Let's Encrypt Certificates" on https://maximilian-boehm.com/en-gb/blog
#
# ===================================================================
server:
  port: 8443
  ssl:
    bundle: "web-server"
    enabled: true
    ciphers:
      - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
      - TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
      - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
      - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
    enabled-protocols: TLSv1.2
  http2:
   enabled: true
spring:
  ssl:
    bundle:
      jks:
        web-server:
          key:
            alias: ${SSL_KEY_ALIAS:Loomify}
            password: ${SSL_KEYSTORE_PASSWORD:S3cr3tP@ssw0rd*123}
          keystore:
            location: ${SSL_KEYSTORE_LOCATION:classpath:tls/server.p12}
            password: ${SSL_KEYSTORE_PASSWORD:S3cr3tP@ssw0rd*123}
            type: "PKCS12"

