name: Frontend CI

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: false
  push:
    branches: [ main ]
    paths:
      - 'client/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - '.github/workflows/frontend-ci.yml'
      - '.github/actions/setup/node/**'
  pull_request:
    paths:
      - 'client/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - '.github/workflows/frontend-ci.yml'
      - '.github/actions/setup/node/**'

env:
  NODE_VERSION: '22'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  lint:
    name: Lint with Biome # Renamed
    runs-on: ubuntu-latest
    # Permissions are inherited from workflow level
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v4

      - name: 🧩 Setup Node.js and pnpm
        uses: ./.github/actions/setup/node
        with:
          node-version: ${{ env.NODE_VERSION }}


      - name: Run Biome with Reviewdog
        uses: mongolyy/reviewdog-action-biome@dbe7192276cbc6cd32369a21f525ed02438c3e26
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workdir: ./client
          reporter: github-pr-review
          fail_on_error: true

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v4

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup/node
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build
        run: pnpm build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-artifacts
          path: |
            client/apps/*/dist/
            client/marketing/dist/
            client/docs/dist/
          retention-days: 7

  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v4

      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup/node
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Test
        run: pnpm test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v4
        if: secrets.CODECOV_TOKEN != ''
        with:
          files: ./coverage/lcov.info # Adjust path if necessary, common for JS projects
          # flags: frontend # Optional
          # name: codecov-frontend # Optional
          # fail_ci_if_error: true # Optional
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
