name: Test PNPM Setup
permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  test-pnpm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # Pinned to v4 commit hash for security
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  # v4



      - name: Setup Node.js and pnpm
        uses: ./.github/actions/setup/node
        with:
          node-version: '22'

      - name: Test pnpm installation
        run: |
          echo "PATH=$PATH"
          which pnpm || echo "pnpm not found"
          pnpm --version
